@echo off
echo Building...
nesasm-vs.exe aoc.asm
echo Writing CHR...
python -c "open('aoc-full.nes', 'wb').write(open('aoc.nes', 'rb').read()+open('biosfnt.chr', 'rb').read()+open('biosfnt.chr', 'rb').read()+open('nss/intro.chr', 'rb').read())"